apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-service
  template:
    metadata:
      labels:
        app: authentication-service
    spec:
      containers:
      - name: authentication-service
        image: 058264221459.dkr.ecr.eu-north-1.amazonaws.com/authentication-service:latest
        ports:
        - containerPort: 5001
        imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Service
metadata:
  name: authentication-service
spec:
  type: LoadBalancer
  ports:
    - port: 5001
      targetPort: 5001
  selector:
    app: authentication-service

